name: notify
description: notify
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter_multi_formatter: ^2.12.4
  intl: ^0.18.1
  file_picker: ^6.0.0
  image_picker: ^1.0.4
  dio: ^5.2.1
  cached_network_image: ^3.2.1
  syncfusion_flutter_datepicker: ^24.2.8
  carousel_slider: ^4.2.1
  flutter_local_notifications: ^17.0.0
  socket_io_client: ^2.0.3+1
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.1.1
  logging: ^1.2.0
  permission_handler: ^11.3.1
  scrollable_positioned_list: ^0.3.8
  pinput: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-VariableFont_wght.ttf
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-SemiBold.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
flutter_intl:
  enabled: true
